/*
 * Copyright (c) 2025 EXALT Technologies.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/types.h>
#include <stm32_ll_dma.h>

#if defined(CONFIG_STM32_HAL2)
#define DMA_LOW_PRIORITY_LOW_WEIGHT    LL_DMA_PRIORITY_LOW_WEIGHT_LOW
#define DMA_LOW_PRIORITY_MID_WEIGHT    LL_DMA_PRIORITY_LOW_WEIGHT_MID
#define DMA_LOW_PRIORITY_HIGH_WEIGHT   LL_DMA_PRIORITY_LOW_WEIGHT_HIGH
#define DMA_HIGH_PRIORITY              LL_DMA_PRIORITY_HIGH
#define MSPI_DMA_SRC_DATAWIDTH_BYTE     LL_DMA_SRC_DATA_WIDTH_BYTE
#define MSPI_DMA_SRC_DATAWIDTH_HALFWORD LL_DMA_SRC_DATA_WIDTH_HALFWORD
#define MSPI_DMA_SRC_DATAWIDTH_WORD     LL_DMA_SRC_DATA_WIDTH_WORD
#define MSPI_DMA_DEST_DATAWIDTH_BYTE     LL_DMA_DEST_DATA_WIDTH_BYTE
#define MSPI_DMA_DEST_DATAWIDTH_HALFWORD LL_DMA_DEST_DATA_WIDTH_HALFWORD
#define MSPI_DMA_DEST_DATAWIDTH_WORD     LL_DMA_DEST_DATA_WIDTH_WORD
#else /* CONFIG_STM32_HAL2 */
#define DMA_LOW_PRIORITY_LOW_WEIGHT    DMA_PRIORITY_LOW
#define DMA_LOW_PRIORITY_MID_WEIGHT    DMA_PRIORITY_MEDIUM
#define DMA_LOW_PRIORITY_HIGH_WEIGHT   DMA_PRIORITY_HIGH
#define DMA_HIGH_PRIORITY              DMA_PRIORITY_VERY_HIGH

#if defined(LL_DMA_SRC_DATAWIDTH_BYTE)
#define MSPI_DMA_SRC_DATAWIDTH_BYTE LL_DMA_SRC_DATAWIDTH_BYTE
#define MSPI_DMA_SRC_DATAWIDTH_HALFWORD LL_DMA_SRC_DATAWIDTH_HALFWORD
#define MSPI_DMA_SRC_DATAWIDTH_WORD LL_DMA_SRC_DATAWIDTH_WORD
#else
#define MSPI_DMA_SRC_DATAWIDTH_BYTE LL_DMA_MDATAALIGN_BYTE
#define MSPI_DMA_SRC_DATAWIDTH_HALFWORD LL_DMA_MDATAALIGN_HALFWORD
#define MSPI_DMA_SRC_DATAWIDTH_WORD LL_DMA_MDATAALIGN_WORD
#endif

#if defined(LL_DMA_DEST_DATAWIDTH_BYTE)
#define MSPI_DMA_DEST_DATAWIDTH_BYTE LL_DMA_DEST_DATAWIDTH_BYTE
#define MSPI_DMA_DEST_DATAWIDTH_HALFWORD LL_DMA_DEST_DATAWIDTH_HALFWORD
#define MSPI_DMA_DEST_DATAWIDTH_WORD LL_DMA_DEST_DATAWIDTH_WORD
#else
#define MSPI_DMA_DEST_DATAWIDTH_BYTE LL_DMA_PDATAALIGN_BYTE
#define MSPI_DMA_DEST_DATAWIDTH_HALFWORD LL_DMA_PDATAALIGN_HALFWORD
#define MSPI_DMA_DEST_DATAWIDTH_WORD LL_DMA_PDATAALIGN_WORD
#endif
#endif /* CONFIG_STM32_HAL2 */

/* Lookup table to set dma priority from the DTS */
const uint32_t mspi_stm32_table_priority[] = {
	DMA_LOW_PRIORITY_LOW_WEIGHT,
	DMA_LOW_PRIORITY_MID_WEIGHT,
	DMA_LOW_PRIORITY_HIGH_WEIGHT,
	DMA_HIGH_PRIORITY,
};

/* Lookup table to set dma channel direction from the DTS */
const uint32_t mspi_stm32_table_direction[] = {
	DMA_MEMORY_TO_MEMORY,
	DMA_MEMORY_TO_PERIPH,
	DMA_PERIPH_TO_MEMORY,
};

const uint32_t mspi_stm32_table_src_size[] = {
	MSPI_DMA_SRC_DATAWIDTH_BYTE,
	MSPI_DMA_SRC_DATAWIDTH_HALFWORD,
	MSPI_DMA_SRC_DATAWIDTH_WORD
};

const uint32_t mspi_stm32_table_dest_size[] = {
	MSPI_DMA_DEST_DATAWIDTH_BYTE,
	MSPI_DMA_DEST_DATAWIDTH_HALFWORD,
	MSPI_DMA_DEST_DATAWIDTH_WORD
};
